USE [master]
GO
/****** Object:  Database [mvccrud4]    Script Date: 7/10/2023 12:29:53 ******/
CREATE DATABASE [mvccrud4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mvccrud4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\mvccrud4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mvccrud4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\mvccrud4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [mvccrud4] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mvccrud4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [mvccrud4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [mvccrud4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [mvccrud4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [mvccrud4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [mvccrud4] SET ARITHABORT OFF 
GO
ALTER DATABASE [mvccrud4] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [mvccrud4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [mvccrud4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [mvccrud4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [mvccrud4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [mvccrud4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [mvccrud4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [mvccrud4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [mvccrud4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [mvccrud4] SET  ENABLE_BROKER 
GO
ALTER DATABASE [mvccrud4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [mvccrud4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [mvccrud4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [mvccrud4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [mvccrud4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [mvccrud4] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [mvccrud4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [mvccrud4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [mvccrud4] SET  MULTI_USER 
GO
ALTER DATABASE [mvccrud4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [mvccrud4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [mvccrud4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [mvccrud4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [mvccrud4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [mvccrud4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [mvccrud4] SET QUERY_STORE = OFF
GO
USE [mvccrud4]
GO
/****** Object:  Table [dbo].[empleado]    Script Date: 7/10/2023 12:29:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[empleado](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[cedula] [int] NULL,
	[nombre] [varchar](50) NULL,
	[apellido] [varchar](50) NULL,
	[telefono] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 7/10/2023 12:29:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[fecha] [date] NULL,
	[clave] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[empleado] ON 
GO
INSERT [dbo].[empleado] ([id], [cedula], [nombre], [apellido], [telefono]) VALUES (1, 89787766, N'ALBERTO ', N'VALENCIA', 979747150)
GO
INSERT [dbo].[empleado] ([id], [cedula], [nombre], [apellido], [telefono]) VALUES (2, 989676767, N'LUIS ', N'CASTRO', 897978678)
GO
SET IDENTITY_INSERT [dbo].[empleado] OFF
GO
SET IDENTITY_INSERT [dbo].[usuarios] ON 
GO
INSERT [dbo].[usuarios] ([id], [nombre], [fecha], [clave]) VALUES (1, N'ROHDE ANCHUNDIA', CAST(N'2023-09-19' AS Date), N'12345')
GO
INSERT [dbo].[usuarios] ([id], [nombre], [fecha], [clave]) VALUES (2, N'MARLE RIOS', CAST(N'2023-10-07' AS Date), N'12345')
GO
SET IDENTITY_INSERT [dbo].[usuarios] OFF
GO
USE [master]
GO
ALTER DATABASE [mvccrud4] SET  READ_WRITE 
GO
